[defaults]
git_remote = "git@github.com:binbandit/dotfiles.git"

[defaults.sync]
pull_interval_minutes = 10
watcher_debounce_ms = 750

[defaults.fish]
paths = [
  "~/Applications",
  "~/Applications/bin",
  "~/Applications/nvim/bin",
  "~/Library/Python/3.9/bin",
  "~/.local/bin",
  "~/.local/share/bob/nvim-bin",
  "~/.mitm_toolkit/bin",
  "~/Developer/go-lang/stack",
  "~/Developer/go-lang/sparrow/bin",
  "~/Developer/rust/zoop/target/release",
  "~/Developer/rust/foreach/target/release",
  "~/Developer/zig/zig/build/stage3/bin",
  "~/Developer/zig/zls/zig-out/bin",
  "~/.goshed/projects/stacking/bin",
  "~/Developer/go-lang/strata-latest",
  "~/Developer/rust/splat/target/debug",
  "~/.bin",
  "~/.cargo/bin",
  "~/.bun/bin"
]

[defaults.fish.env]
BUN_INSTALL = "~/.bun"
PNPM_HOME = "~/Library/pnpm"
OPENAI_MODEL = "gpt-5-nano"
OPENAI_URL = "https://api.openai.com/v1/"
OPENAI_TIMEOUT = "4096"
OPENAI_MAX_TOKENS = "272000"

[defaults.fish.plugins]
fisherfile = [
  "jorgebucaran/fisher",
  "patrickf1/fzf.fish",
  "edc/bass",
  "laughedelic/pisces",
  "jorgebucaran/replay.fish",
  "vincentjames501/fish-kill-on-port"
]

[defaults.fish.proxies]
http = ""
https = ""
no_proxy = ""

[[defaults.fish.abbreviations]]
name = "yl"
expansion = "yarn list"

[[defaults.fish.abbreviations]]
name = "yad"
expansion = "yarn add -D"

[[defaults.fish.abbreviations]]
name = "ya"
expansion = "yarn add"

[[defaults.fish.abbreviations]]
name = "y"
expansion = "yarn"

[[defaults.fish.abbreviations]]
name = "yb"
expansion = "yarn build"

[[defaults.fish.abbreviations]]
name = "yd"
expansion = "yarn dev"

[[defaults.fish.abbreviations]]
name = "ys"
expansion = "yarn start"

[[defaults.fish.abbreviations]]
name = "yt"
expansion = "yarn test"

[[defaults.fish.abbreviations]]
name = "p"
expansion = "pnpm"

[[defaults.fish.abbreviations]]
name = "pad"
expansion = "pnpm add -D"

[[defaults.fish.abbreviations]]
name = "pa"
expansion = "pnpm add"

[[defaults.fish.abbreviations]]
name = "pb"
expansion = "pnpm build"

[[defaults.fish.abbreviations]]
name = "pd"
expansion = "pnpm dev"

[[defaults.fish.abbreviations]]
name = "ps"
expansion = "pnpm start"

[[defaults.fish.abbreviations]]
name = "pt"
expansion = "pnpm test"

[[defaults.fish.abbreviations]]
name = "pi"
expansion = "pnpm install"

[[defaults.fish.abbreviations]]
name = "pp"
expansion = "pnpm pack | xargs -I {} echo \"$(pwd)/{}\" | pbcopy"

[[defaults.fish.abbreviations]]
name = "po"
expansion = "pnpm orchestrator"

[[defaults.fish.abbreviations]]
name = "cpad"
expansion = "clear; pnpm add -D"

[[defaults.fish.abbreviations]]
name = "cpa"
expansion = "clear; pnpm add"

[[defaults.fish.abbreviations]]
name = "cpb"
expansion = "clear; pnpm build"

[[defaults.fish.abbreviations]]
name = "cpd"
expansion = "clear; pnpm dev"

[[defaults.fish.abbreviations]]
name = "cps"
expansion = "clear; pnpm start"

[[defaults.fish.abbreviations]]
name = "cpt"
expansion = "clear; pnpm test"

[[defaults.fish.abbreviations]]
name = "cpi"
expansion = "clear; pnpm install"

[[defaults.fish.abbreviations]]
name = "cpp"
expansion = "clear; pnpm pack | xargs -I {} echo \"$(pwd)/{}\" | pbcopy"

[[defaults.fish.abbreviations]]
name = "cpo"
expansion = "clear; pnpm orchestrator"

[[defaults.fish.abbreviations]]
name = "ppb"
expansion = "pnpm install; pnpm build"

[[defaults.fish.abbreviations]]
name = "ppd"
expansion = "pnpm install; pnpm dev"

[[defaults.fish.abbreviations]]
name = "pps"
expansion = "pnpm install; pnpm start"

[[defaults.fish.abbreviations]]
name = "ppt"
expansion = "pnpm install; pnpm test"

[[defaults.fish.abbreviations]]
name = "ppo"
expansion = "pnpm install; pnpm orchestrator"

[[defaults.fish.abbreviations]]
name = "cppb"
expansion = "clear; pnpm install; pnpm build"

[[defaults.fish.abbreviations]]
name = "cppd"
expansion = "clear; pnpm install; pnpm dev"

[[defaults.fish.abbreviations]]
name = "cpps"
expansion = "clear; pnpm install; pnpm start"

[[defaults.fish.abbreviations]]
name = "cppt"
expansion = "clear; pnpm install; pnpm test"

[[defaults.fish.abbreviations]]
name = "cppo"
expansion = "clear; pnpm install; pnpm orchestrator"

[[defaults.fish.abbreviations]]
name = "gs"
expansion = "git status"

[[defaults.fish.abbreviations]]
name = "gp"
expansion = "git pull"

[[defaults.fish.abbreviations]]
name = "gpu"
expansion = "git push"

[[defaults.fish.abbreviations]]
name = "gc"
expansion = "git commit -a -m"

[[defaults.fish.abbreviations]]
name = "ga"
expansion = "git add"

[[defaults.fish.abbreviations]]
name = "gr"
expansion = "go run"

[[defaults.fish.abbreviations]]
name = "gb"
expansion = "go build"

[[defaults.fish.abbreviations]]
name = "cgr"
expansion = "clear; go run"

[[defaults.fish.abbreviations]]
name = "cgb"
expansion = "clear; go build"

[[defaults.fish.abbreviations]]
name = "cwd"
expansion = "pwd | pbcopy"

[[defaults.fish.abbreviations]]
name = "z"
expansion = "emacsclient -c"

[[defaults.fish.abbreviations]]
name = "n"
expansion = "nvim"

[[defaults.fish.abbreviations]]
name = "c"
expansion = "cargo"

[[defaults.fish.abbreviations]]
name = "ca"
expansion = "cargo add"

[[defaults.fish.abbreviations]]
name = "cr"
expansion = "cargo run"

[[defaults.fish.abbreviations]]
name = "cb"
expansion = "cargo build"

[[defaults.fish.abbreviations]]
name = "x"
expansion = "pnpm dlx"

[defaults.packages.macos]
brewfile = ".config/homebrew/Brewfile"

[defaults.packages.arch]
pacman_file = "packages-arch.txt"

[defaults.mise.tools]
node = "lts"
pnpm = "latest"
go = "latest"
bun = "latest"

[defaults.uv]
python_version = "3.12"

[[defaults.custom_tools.cargo]]
name = "tap"
git = "https://github.com/crazywolf132/tap.git"

[[defaults.custom_tools.cargo]]
name = "sg"
git = "https://github.com/sage-scm/sage.git"
bin = "sg"

[[defaults.custom_tools.cargo]]
name = "keychainctl"
git = "https://github.com/binbandit/keychainctl.git"

[hosts."Braydens-MacBook-Pro"]
roles = ["personal", "mac"]

[hosts."Braydens-MacBook-Pro".sync]
pull_interval_minutes = 5

[hosts."Braydens-MacBook-Pro".fish.env]
OPENAI_MODEL = "gpt-5-nano"

[hosts."EPZ-D3YJQFV0WJ"]
roles = ["work", "mac"]

[hosts."work-mac-template"]
roles = ["work", "mac"]

[hosts."work-mac-template".fish.proxies]
http = "http://proxy.example.com:8080"
https = "http://proxy.example.com:8080"
no_proxy = "localhost,127.0.0.1,.example.com"
