abbr yl 'yarn list'
abbr yad 'yarn add -D'
abbr ya 'yarn add'
abbr y 'yarn'
abbr yb 'yarn build'
abbr yd 'yarn dev'
abbr ys 'yarn start'
abbr yt 'yarn test'

abbr p 'pnpm'
abbr pad 'pnpm add -D'
abbr pa 'pnpm add'
abbr pb 'pnpm build'
abbr pd 'pnpm dev'
abbr ps 'pnpm start'
abbr pt 'pnpm test'
abbr pi 'pnpm install'
abbr pp 'pnpm pack | xargs -I {} echo "$(pwd)/{}" | pbcopy'
abbr po 'pnpm orchestrator'

abbr cpad 'clear; pnpm add -D'
abbr cpa 'clear; pnpm add'
abbr cpb 'clear; pnpm build'
abbr cpd 'clear; pnpm dev'
abbr cps 'clear; pnpm start'
abbr cpt 'clear; pnpm test'
abbr cpi 'clear; pnpm install'
abbr cpp 'clear; pnpm pack | xargs -I {} echo "$(pwd)/{}" | pbcopy'
abbr cpo 'clear; pnpm orchestrator'

abbr ppb 'pnpm install; pnpm build'
abbr ppd 'pnpm install; pnpm dev'
abbr pps 'pnpm install; pnpm start'
abbr ppt 'pnpm install; pnpm test'
abbr ppo 'pnpm install; pnpm orchestrator'

abbr cppb 'clear; pnpm install; pnpm build'
abbr cppd 'clear; pnpm install; pnpm dev'
abbr cpps 'clear; pnpm install; pnpm start'
abbr cppt 'clear; pnpm install; pnpm test'
abbr cppo 'clear; pnpm install; pnpm orchestrator'

abbr gs 'git status'
abbr gp 'git pull'
abbr gpu 'git push'
abbr gc 'git commit -a -m'
abbr ga 'git add'

abbr gr 'go run'
abbr gb 'go build'
abbr cgr 'clear; go run'
abbr cgb 'clear; go build'
abbr gm 'go mod'
abbr gi 'go install'
abbr gt 'go test'
abbr gmt 'go mod tidy'

abbr cwd 'pwd | pbcopy'

abbr z 'emacsclient -c'
abbr n 'nvim'

abbr c 'cargo'
abbr ca 'cargo add'
abbr cr 'cargo run'
abbr cb 'cargo build'

abbr x 'pnpm dlx'
abbr l 'eza --icons'
