local M = {}

local leader_groups = {
  { "<leader>b",        group = "Buffers" },
  { "<leader>g",        group = "Git & GitHub" },
  { "<leader>q",        group = "Quit" },
  { "<leader>s",        group = "Splits" },
  { "<leader>t",        group = "Toggles" },
  { "<leader>w",        group = "Write" },
  { "<leader>?",        group = "Help" },
  { "<leader>c",        group = "Crates" },
  { "<leader>l",        group = "LSP" },
  { "<leader>o",        group = "Oil" },
  { "<leader>h",        group = "Harpoon" },
  { "<leader>/",        desc = "Live Grep" },
  { "<leader>|",        desc = "Vertical Split" },
  { "<leader>`",        desc = "Alternate Buffer" },
  { "<leader>hc",       desc = "Clear Highlight" },
  { "<leader>ai",       desc = "Toggle AI Assistant" },
  { "<leader>bd",       desc = "Close Buffer" },
  { "<leader>bb",       desc = "Buffer Manager" },
  { "<leader>w",        desc = "Write buffer" },
  { "<leader>qq",       desc = "Quit" },
  { "<leader>ti",       desc = "Toggle inlay hints" },
  { "<leader>sv",       desc = "Split Right" },
  { "<leader>sh",       desc = "Split Below" },
  { "<leader>gg",       desc = "Lazygit" },
  { "<leader>gb",       desc = "Git Blame Line" },
  { "<leader>go",       desc = "Octo actions" },
  { "<leader>gi",       desc = "List Issues" },
  { "<leader>gp",       desc = "List Pull Requests" },
  { "<leader>gN",       desc = "New Issue" },
  { "<leader>gn",       desc = "Notifications" },
  { "<leader>gs",       desc = "Stage git hunk" },
  { "<leader>gr",       desc = "Reset git hunk" },
  { "<leader>gS",       desc = "Stage buffer" },
  { "<leader>gP",       desc = "Preview git hunk" },
  { "<leader>gu",       desc = "Undo stage hunk" },
  { "<leader>gB",       desc = "Git blame (full)" },
  { "<leader>ps",       desc = "Open Store" },
  { "<leader>st",       desc = "Todo quickfix" },
  { "<leader>tw",       desc = "Toggle Twilight" },
  { "<leader>tb",       desc = "Toggle word/boolean" },
  { "<leader>tt",       desc = "Toggle task state" },
  { "<leader>tc",       desc = "Mark task complete" },
  { "<leader>tu",       desc = "Mark task incomplete" },
  { "<leader>tn",       desc = "New task below" },
  { "<leader>ta",       desc = "Archive checked tasks" },
  { "<leader>tr",       desc = "Convert task to text" },
  { "<leader>tR",       desc = "Strip task metadata" },
  { "<leader>u",        group = "UI" },
  { "<leader>uj",       desc = "Use Jellybeans" },
  { "<leader>ur",       desc = "Use Rose Pine" },
  { "<leader>ub",       desc = "Use Backpack" },
  { "<leader>ut",       desc = "Cycle theme" },
  { "<leader>uu",       desc = "Toggle Undotree" },
  { "<leader>vd",       desc = "Toggle venn mode" },
  { "<leader>vb",       desc = "Draw venn box" },
  { "<leader>ld",       desc = "Diagnostics (Trouble)" },
  { "<leader>le",       desc = "Errors (Trouble)" },
  { "<leader>lf",       desc = "Format" },
  { "<leader>rn",       desc = "Rename" },
  { "<leader>ca",       desc = "Code Action" },
  { "<leader>cu",       desc = "Update crate under cursor" },
  { "<leader>cU",       desc = "Update all crates" },
  { "<leader>cv",       desc = "Show crate versions" },
  { "<leader>cf",       desc = "Show crate features" },
  { "<leader>cd",       desc = "Open crate documentation" },
  { "<leader>o",        desc = "Open oil" },
  { "<leader>e",        desc = "Open oil" },
  { "<leader>ha",       desc = "Harpoon add file" },
  { "<leader>he",       desc = "Harpoon toggle menu" },
  { "<leader>h1",       desc = "Harpoon goto 1" },
  { "<leader>h2",       desc = "Harpoon goto 2" },
  { "<leader>h3",       desc = "Harpoon goto 3" },
  { "<leader>h4",       desc = "Harpoon goto 4" },
  { "<leader>hp",       desc = "Harpoon previous" },
  { "<leader>hn",       desc = "Harpoon next" },
  { "gl",               desc = "Line Diagnostics" },
  { "gd",               desc = "Goto Definition" },
  { "gD",               desc = "Goto Declaration" },
  { "gr",               desc = "Goto References" },
  { "gi",               desc = "Goto Implementation" },
  { "K",                desc = "Hover" },
  { "]h",               desc = "Next git hunk" },
  { "[h",               desc = "Previous git hunk" },
  { "[t",               desc = "Previous todo comment" },
  { "]t",               desc = "Next todo comment" },
  { "ff",               desc = "Find files" },
  { "<leader><leader>", desc = "Find files" },
  { "<C-h>",            desc = "Navigate left" },
  { "<C-j>",            desc = "Navigate down" },
  { "<C-k>",            desc = "Navigate up" },
  { "<C-l>",            desc = "Navigate right" },
  { "<C-a>",            desc = "Select entire file" },
  { "<C-]>",            desc = "AI accept suggestion",     mode = "i" },
}

function M.setup()
  local wk = require("which-key")
  wk.setup({
    notify = false,
    plugins = {
      marks = false,
      registers = false,
    },
    win = {
      border = "rounded",
    },
  })
  wk.add(leader_groups)
end

return M
