theme = "amberwood"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-s = ":w"
Meta-s = ":w"

[keys.insert]
C-s = ":w"
Meta-s = ":w"
