theme = "amberwood"

[editor]
auto-save = true
soft-wrap.enable = true
middle-click-paste = false
bufferline = "multiple"
cursorline = true
line-number = "relative"
rulers = [120]
true-color = true
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true

[keys.normal]
K = "hover"
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
"A-/" = "repeat_last_motion"
C-s = ":w"
C-w = ":buffer-close"
Meta-s = ":w"

[keys.normal.space]
space = "file_picker"

[keys.normal.f]
f = "file_picker"

[keys.normal.q]
q = ":quit-all"

[keys.select]
A-x = "extend_to_line_bounds"
X = "select_line_above"

[keys.insert]
C-s = ":w"
Meta-s = ":w"

